version: '3'

services:
  web:
    build: .
    command: gunicorn uuidresolver.wsgi:application --bind 0.0.0.0:81
    expose: 
      - 81
    env_file:
      - ./prod.env
    volumes:
      - .:/code

networks:
  default:
    external:
      name: nginx-proxy
