version: '3'

services:
  web:
    image: resolver-populate
    build: .
    command: python manage.py runserver 0.0.0.0:80
    # bash -c "python manage.py migrate && python manage.py populate_resolver"
    expose: 
      - 80
    env_file:
      - ./test.env
    volumes:
      - .:/code

networks:
  default:
    external:
      name: nginx-proxy
