version: '3'

services:
  spark:
    image: docker.io/bitnami/spark:3.3
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
  spark-worker:
    image: docker.io/bitnami/spark:3.3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  web:
    restart: always
    build: .
    #command: gunicorn resolver.wsgi:application --bind 0.0.0.0:80 --reload
    #command: python manage.py runserver 0.0.0.0:80
    #command: python manage.py populate_resolver --skip
    #command: /bin/bash
    #stdin_open: true
    tty: true
    #command:
    expose: 
      - 80
    env_file:
      - ./prod.env
    volumes:
      - .:/code

networks:
  default:
    external:
      name: nginx-proxy
