version: '3'

services:
  web:
    restart: always
    build: .
    #command: gunicorn uuidresolver.wsgi:application --bind 0.0.0.0:80 --reload
    command: python manage.py runserver 0.0.0.0:80
    expose: 
      - 80
    env_file:
      - ./prod.env
    volumes:
      - .:/code

networks:
  default:
    external:
      name: nginx-proxy
