version: '3'

services:
  db:
    image: postgres
    shm_size: 5g
    environment:
        - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - "5432"
  web:
    image: resolver-populate-test
    build: .
    command: sh -c "sleep 5 && python manage.py test"
    environment:
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db
