version: '3'

services:
  web:
    image: resolver-populate
    build: .
    command: python manage.py test
    env_file:
      - ./test.env
    volumes:
      - .:/code

networks:
  default:
    external:
      name: nginx-proxy
