# Generated by Django 3.1 on 2020-08-21 10:25

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResolvableObject',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('type', models.CharField(max_length=200)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.dataset')),
            ],
        ),
        migrations.AddIndex(
            model_name='resolvableobject',
            index=django.contrib.postgres.indexes.GinIndex(fields=['data'], name='website_res_data_00a3fa_gin'),
        ),
    ]
