# Generated by Django 3.1.13 on 2022-07-15 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_resolvableobject_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resolvableobject',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
