# Generated by Django 3.0.8 on 2020-07-29 09:29

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DarwinCoreObject',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('changed_date', models.DateField()),
                ('darwin_core_object', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.DarwinCoreObject')),
            ],
        ),
        migrations.AddIndex(
            model_name='darwincoreobject',
            index=django.contrib.postgres.indexes.GinIndex(fields=['data'], name='website_dar_data_12a5e6_gin'),
        ),
    ]
