# Generated by Django 3.0.8 on 2020-07-16 09:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='darwincoreobject',
            name='deleted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('changed_date', models.DateField()),
                ('darwin_core_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.DarwinCoreObject')),
            ],
        ),
    ]
