# Generated by Django 2.2.4 on 2019-08-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='darwincoreobject',
            index=models.Index(fields=['uuid'], name='website_dar_uuid_8f8c5b_idx'),
        ),
    ]
