# Generated by Django 3.1.14 on 2023-01-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20220715_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolvableobject',
            name='parent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
