# Generated by Django 3.1.13 on 2022-07-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('populator', '0001_history_resolvableobjectmigration_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolvableobjectmigration',
            name='parent_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='changed_date',
            field=models.DateField(auto_now=True),
        ),
    ]
