# Generated by Django 3.1.14 on 2023-01-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('populator', '0002_auto_20220714_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resolvableobjectmigration',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
